name: Workflow for openrtm-lua code coverage analysis
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_2004_lua53_cov]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run unittest
        run:  | 
                export OPENRTMLUA_IMAGE=openrtm-lua:${{matrix.os}}-$(date +%s)
                docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag $OPENRTMLUA_IMAGE
                docker run -v /home/runner/work/RTM-Lua/RTM-Lua/share:/root/share $OPENRTMLUA_IMAGE
                curl -Os https://uploader.codecov.io/latest/linux/codecov
                chmod +x codecov
                ./codecov
