name: Workflow for openrtm-lua static code analysis
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_2004_lua53_static_code_analysis]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run static code analysis
        run:  | 
                export OPENRTMLUA_IMAGE=openrtm-lua:${{matrix.os}}-$(date +%s)
                docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag $OPENRTMLUA_IMAGE
                docker run $OPENRTMLUA_IMAGE
