name: Workflow for Codecov openrtm-lua unit-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_2004]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Lua 5.3
        run:  | 
                export OPENRTMLUA_IMAGE=openrtm-lua:${{matrix.os}}-$(date +%s)
                docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag $OPENRTMLUA_IMAGE
                mkdir /home/runner/work/RTM-Lua/RTM-Lua/share
                docker run -v /home/runner/work/RTM-Lua/RTM-Lua/share:/root/share $OPENRTMLUA_IMAGE
                
