name: Workflow for Codecov openrtm-lua unit-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_2004]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set image name
        run: export OPENRTMLUA_IMAGE=openrtm-lua:${{matrix.os}}-$(date +%s)
      - name: Set up Lua 5.3
        run: docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag $OPENRTMLUA_IMAGE
      - name: test
        run: docker run $OPENRTMLUA_IMAGE
