name: Workflow for Codecov openrtm-lua unit-test
on: [push, pull_request]
jobs:
  run:
    runs-on: [ubuntu_2004]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Lua 5.3
        run: docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag openrtm-lua:${{matrix.os}}-$(date +%s)
